In [1]:
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 1 Loading the data
NB: the json need to be a list of json elements as dictionary. We need to add the **brackets []** and the **coma** to separate each element

In [2]:
with open("../yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_business.json") as json_file:
    data_business = json.load(json_file)


In [3]:
data_business[35]

{u'attributes': {u'Accepts Credit Cards': True,
  u'Alcohol': u'full_bar',
  u'Ambience': {u'casual': True,
   u'classy': False,
   u'divey': False,
   u'hipster': False,
   u'intimate': False,
   u'romantic': False,
   u'touristy': False,
   u'trendy': False,
   u'upscale': False},
  u'Attire': u'casual',
  u'BYOB': False,
  u'BYOB/Corkage': u'yes_free',
  u'Caters': False,
  u'Corkage': False,
  u'Delivery': False,
  u'Good For': {u'breakfast': False,
   u'brunch': False,
   u'dessert': False,
   u'dinner': False,
   u'latenight': True,
   u'lunch': False},
  u'Good For Groups': True,
  u'Good For Kids': False,
  u'Good for Kids': True,
  u'Has TV': True,
  u'Noise Level': u'very_loud',
  u'Outdoor Seating': False,
  u'Parking': {u'garage': False,
   u'lot': True,
   u'street': False,
   u'valet': False,
   u'validated': False},
  u'Price Range': 2,
  u'Take-out': True,
  u'Takes Reservations': True,
  u'Waiter Service': True,
  u'Wheelchair Accessible': True},
 u'business_id': u'sbW

Somes features need to be droped:
* 'full_address', 'city': the state and latitude/longitude already stand for the geographical position. Maybe the street could eb considered, but then will need to be convert...
* 'name': need to find how to use it (add features count to find a word realted to categories in the name?)
* 'type': stands for the data type (here it's business)

Somes features are droped but may be useful, we need to think about how to use them:
* 'attributes': issue is the unstructured nature
* 'hours': the checkin seems to be enough
* 'neighborhoods': many missing values in this column

In [4]:
business_list = []
    
for b in data_business:
    d = b.copy()
    
    # Dropping unconsidered features
    d.pop('hours')
    #d.pop('attributes')
    d.pop('neighborhoods')
    d.pop('type')
    d.pop('full_address')
    d.pop('name')
    d.pop('city')
    
    
    business_list.append(d)
    
business=pd.DataFrame(business_list)
# Changing the index
business = business.set_index('business_id')

business.head(5)

attributes  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA                     {u'By Appointment Only': True}   
UsFtqoBl7naz8AVUBZMjQQ  {u'Happy Hour': True, u'Accepts Credit Cards':...   
cE27W9VPgO88Qxe4ol6y_g                           {u'Good for Kids': True}   
HZdLhv6COCleJMo7nPl-RA                                                 {}   
mVHrayjG3uZ_RLHkLj-AMg  {u'Alcohol': u'full_bar', u'Noise Level': u'av...   

                                                               categories  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA                        [Doctors, Health & Medical]   
UsFtqoBl7naz8AVUBZMjQQ                                        [Nightlife]   
cE27W9VPgO88Qxe4ol6y_g                     [Active Life, Mini Golf, Golf]   
HZdLhv6COCleJMo7nPl-RA  [Shopping, Home Services, Internet Service Pro...   
mVHrayjG3uZ_RLHkLj-AMg  [Bars, American (New), Nightlife, Lounges, Res...   

                         latitude   longitude   open  review_count  stars  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA  33.499313 -111.983758   True             9    3.5   
UsFtqoBl7naz8AVUBZMjQQ  40.350519  -79.886930   True             4    3.5   
cE27W9VPgO88Qxe4ol6y_g  40.356896  -80.015910  False             5    2.5   
HZdLhv6COCleJMo7nPl-RA  40.357620  -80.059980   True             3    3.5   
mVHrayjG3uZ_RLHkLj-AMg  40.408735  -79.866351   True            11    4.5   

                       state  
business_id                   
vcNAWiLM4dR7D2nwwJ7nCA    AZ  
UsFtqoBl7naz8AVUBZMjQQ    PA  
cE27W9VPgO88Qxe4ol6y_g    PA  
HZdLhv6COCleJMo7nPl-RA    PA  
mVHrayjG3uZ_RLHkLj-AMg    PA

In [5]:
with open("../yelp_dataset_challenge_academic_dataset/yelp_academic_dataset_checkin.json") as json_file:
    data_checkin = json.load(json_file)


In [6]:
data_checkin[0]

{u'business_id': u'cE27W9VPgO88Qxe4ol6y_g',
 u'checkin_info': {u'10-0': 1,
  u'13-0': 1,
  u'13-3': 1,
  u'14-6': 1,
  u'17-3': 1,
  u'17-6': 1,
  u'18-4': 1,
  u'7-5': 1,
  u'9-5': 1},
 u'type': u'checkin'}

In [7]:
checkin_list = []

for c in data_checkin:
    d = {}
    d['business_id'] = c['business_id']
    for k,v in c['checkin_info'].iteritems():
        d[k] = v
    checkin_list.append(d)
    
checkin=pd.DataFrame(checkin_list)
checkin = checkin.set_index('business_id')

# Change Nan to 0 in the checking
checkin = checkin.fillna(0)

checkin.head(10)

0-0  0-1  0-2  0-3  0-4  0-5  0-6  1-0  1-1  1-2 ...   \
business_id                                                              ...    
cE27W9VPgO88Qxe4ol6y_g    0    0    0    0    0    0    0    0    0    0 ...    
mVHrayjG3uZ_RLHkLj-AMg    0    0    0    0    0    0    0    0    0    0 ...    
KayYbHCt-RkbGcPdGOThNg    0    0    0    0    0    0    0    0    0    0 ...    
wJr6kSA5dchdgOdwH6dZ2w    0    0    0    0    0    0    0    0    0    0 ...    
yXuao0pFz1AxB21vJjDf5w    0    0    0    0    0    0    0    0    0    0 ...    
fNGIbpazjTRdXgwRY_NIXA    0    0    0    0    0    0    0    0    0    0 ...    
b9WZJp5L1RZr4F1nxclOoQ    0    0    0    0    0    0    0    0    0    0 ...    
zaXDakTd3RXyOa7sMrUE1g    0    0    0    0    0    0    0    0    0    0 ...    
zgy27FSnvwdINfk5cXBIyQ    0    0    0    0    0    0    0    0    0    0 ...    
WETE_LykpcnrC1sFcQ5EGg    0    0    0    0    0    0    0    0    0    0 ...    

                        8-4  8-5  8-6  9-0  9-1  9-2  9-3  9-4  9-5  9-6  
business_id                                                               
cE27W9VPgO88Qxe4ol6y_g    0    0    0    0    0    0    0    0    1    0  
mVHrayjG3uZ_RLHkLj-AMg    0    0    0    0    0    0    0    0    1    0  
KayYbHCt-RkbGcPdGOThNg    1    0    0    0    1    0    0    3    0    0  
wJr6kSA5dchdgOdwH6dZ2w    0    0    0    1    0    0    0    0    0    0  
yXuao0pFz1AxB21vJjDf5w    0    0    0    0    0    0    0    1    0    0  
fNGIbpazjTRdXgwRY_NIXA    0    0    0    1    0    0    0    1    0    0  
b9WZJp5L1RZr4F1nxclOoQ    2    3    4    2    3    1    2    4    4    1  
zaXDakTd3RXyOa7sMrUE1g    0    2    0    0    0    0    0    1    0    0  
zgy27FSnvwdINfk5cXBIyQ    0    0    0    0    0    0    0    0    1    0  
WETE_LykpcnrC1sFcQ5EGg    0    0    0    0    0    0    0    0    0    0  

[10 rows x 168 columns]

In [8]:
# ## Joining the dataframes
business_df = business.merge(checkin, how='left', right_index=True, left_index=True)
business_df.head()

attributes  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA                     {u'By Appointment Only': True}   
UsFtqoBl7naz8AVUBZMjQQ  {u'Happy Hour': True, u'Accepts Credit Cards':...   
cE27W9VPgO88Qxe4ol6y_g                           {u'Good for Kids': True}   
HZdLhv6COCleJMo7nPl-RA                                                 {}   
mVHrayjG3uZ_RLHkLj-AMg  {u'Alcohol': u'full_bar', u'Noise Level': u'av...   

                                                               categories  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA                        [Doctors, Health & Medical]   
UsFtqoBl7naz8AVUBZMjQQ                                        [Nightlife]   
cE27W9VPgO88Qxe4ol6y_g                     [Active Life, Mini Golf, Golf]   
HZdLhv6COCleJMo7nPl-RA  [Shopping, Home Services, Internet Service Pro...   
mVHrayjG3uZ_RLHkLj-AMg  [Bars, American (New), Nightlife, Lounges, Res...   

                         latitude   longitude   open  review_count  stars  \
business_id                                                                 
vcNAWiLM4dR7D2nwwJ7nCA  33.499313 -111.983758   True             9    3.5   
UsFtqoBl7naz8AVUBZMjQQ  40.350519  -79.886930   True             4    3.5   
cE27W9VPgO88Qxe4ol6y_g  40.356896  -80.015910  False             5    2.5   
HZdLhv6COCleJMo7nPl-RA  40.357620  -80.059980   True             3    3.5   
mVHrayjG3uZ_RLHkLj-AMg  40.408735  -79.866351   True            11    4.5   

                       state  0-0  0-1 ...   8-4  8-5  8-6  9-0  9-1  9-2  \
business_id                            ...                                  
vcNAWiLM4dR7D2nwwJ7nCA    AZ  NaN  NaN ...   NaN  NaN  NaN  NaN  NaN  NaN   
UsFtqoBl7naz8AVUBZMjQQ    PA  NaN  NaN ...   NaN  NaN  NaN  NaN  NaN  NaN   
cE27W9VPgO88Qxe4ol6y_g    PA    0    0 ...     0    0    0    0    0    0   
HZdLhv6COCleJMo7nPl-RA    PA  NaN  NaN ...   NaN  NaN  NaN  NaN  NaN  NaN   
mVHrayjG3uZ_RLHkLj-AMg    PA    0    0 ...     0    0    0    0    0    0   

                        9-3  9-4  9-5  9-6  
business_id                                 
vcNAWiLM4dR7D2nwwJ7nCA  NaN  NaN  NaN  NaN  
UsFtqoBl7naz8AVUBZMjQQ  NaN  NaN  NaN  NaN  
cE27W9VPgO88Qxe4ol6y_g    0    0    1    0  
HZdLhv6COCleJMo7nPl-RA  NaN  NaN  NaN  NaN  
mVHrayjG3uZ_RLHkLj-AMg    0    0    1    0  

[5 rows x 176 columns]

In [9]:
# Droping the business with Nan values of checkin
business_df = business_df.dropna(how='any')

In [10]:
business_df.categories

business_id
cE27W9VPgO88Qxe4ol6y_g                       [Active Life, Mini Golf, Golf]
mVHrayjG3uZ_RLHkLj-AMg    [Bars, American (New), Nightlife, Lounges, Res...
KayYbHCt-RkbGcPdGOThNg    [Bars, American (Traditional), Nightlife, Rest...
wJr6kSA5dchdgOdwH6dZ2w    [Burgers, Breakfast & Brunch, American (Tradit...
yXuao0pFz1AxB21vJjDf5w                                      [Food, Grocery]
fNGIbpazjTRdXgwRY_NIXA    [Bars, American (Traditional), Nightlife, Loun...
b9WZJp5L1RZr4F1nxclOoQ                    [Breakfast & Brunch, Restaurants]
zaXDakTd3RXyOa7sMrUE1g                                 [Cafes, Restaurants]
zgy27FSnvwdINfk5cXBIyQ    [Hotels & Travel, Event Planning & Services, H...
WETE_LykpcnrC1sFcQ5EGg          [Pubs, Irish, Nightlife, Bars, Restaurants]
SQ0j7bgSTazkVQlF5AnqyQ                               [Chinese, Restaurants]
wqu7ILomIOPSduRwoWp4AQ    [Breakfast & Brunch, American (Traditional), R...
P1fJb2WQ1mXoiudj8UE44w                               [Restaurants, Italian]


## 2 Restriction on restaurants: 

In [11]:
# Restricting to the restaurants
restaurants = business_df[business_df['categories'].apply(lambda x: 'Restaurants' in x)]

In [12]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18640 entries, mVHrayjG3uZ_RLHkLj-AMg to qrgod2lrYnxHwNWC_YYTyQ
Columns: 176 entries, attributes to 9-6
dtypes: bool(1), float64(171), int64(1), object(3)
memory usage: 25.0+ MB


In [13]:
# Study on the categories

restaurant_categories = restaurants.categories.values
restaurant_categories_set = set([c for cs in restaurant_categories for c in cs])
nationalities = []
with open('nationality_list.txt') as f:
    for line in f:
        # Remove the special character \n
        nat = line[:-1]
        # Consider only those in the set
        if nat in restaurant_categories_set:
            nationalities.append(nat)
nationalities_map = {k:i+1 for i,k in enumerate(nationalities)}
nationalities_map

{'Afghan': 1,
 'Argentine': 2,
 'Australian': 4,
 'Austrian': 3,
 'Bangladeshi': 5,
 'Belgian': 6,
 'Brazilian': 7,
 'British': 8,
 'Cambodian': 9,
 'Chinese': 10,
 'Colombian': 11,
 'Czech': 12,
 'Egyptian': 13,
 'Ethiopian': 15,
 'French': 16,
 'German': 17,
 'Greek': 18,
 'Hungarian': 19,
 'Indian': 20,
 'Indonesian': 21,
 'Irish': 22,
 'Italian': 23,
 'Japanese': 24,
 'Malaysian': 25,
 'Mexican': 26,
 'Moroccan': 27,
 'Pakistani': 28,
 'Peruvian': 29,
 'Polish': 30,
 'Portuguese': 31,
 'Russian': 32,
 'Salvadoran': 14,
 'Scottish': 33,
 'Singaporean': 34,
 'Spanish': 35,
 'Thai': 36,
 'Turkish': 37,
 'Vietnamese': 38}

In [14]:
# Label the class

def get_target(categories, n_map):
    for c in categories:
        if c in n_map:
            return n_map[c]
    return 0

restaurants['target'] = restaurants.apply(lambda x: get_target(x['categories'], nationalities_map), axis=1)

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [15]:
# Study on the attributes
import collections

attributes_keys = [k for attributes in restaurants.attributes.values for k in attributes.keys()]
len(attributes_keys)

counter = collections.Counter(attributes_keys)
counter.most_common(20)

[(u'Accepts Credit Cards', 18070),
 (u'Price Range', 17889),
 (u'Good For Groups', 17782),
 (u'Good for Kids', 17734),
 (u'Attire', 17677),
 (u'Take-out', 17652),
 (u'Takes Reservations', 17426),
 (u'Outdoor Seating', 17301),
 (u'Delivery', 17263),
 (u'Good For', 16881),
 (u'Parking', 16515),
 (u'Waiter Service', 16482),
 (u'Has TV', 16461),
 (u'Alcohol', 16243),
 (u'Ambience', 15785),
 (u'Noise Level', 15762),
 (u'Wi-Fi', 13435),
 (u'Caters', 12385),
 (u'Wheelchair Accessible', 9494),
 (u'Drive-Thru', 2471)]

In [16]:
# Picking the top attributes
top_attributes = [c[0] for c in counter.most_common(16)]

# Drop irrelevant attributes (also because their format is dictionnaries)
top_attributes.pop(top_attributes.index('Good For'))
top_attributes.pop(top_attributes.index('Parking'))
top_attributes.pop(top_attributes.index('Ambience'))

for c in top_attributes:
    restaurants[c] = restaurants.apply(lambda x: x['attributes'][c] if c in x['attributes'].keys() else np.nan, axis=1)

# Dropping the na values (First draft)
# To handle missing values: estimate the missing values based on knn or latent features model
restaurants_clean = restaurants.dropna(how='any')

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [17]:
def is_categorical(unique):
    if len(unique) > 2 and not isinstance(unique[0], float) and not isinstance(unique[0], bool) and not isinstance(unique[0], int):
        return True
    else:
        return False

# Listing the categorical features
categorical = []
for c in restaurants_clean.columns.values:
    if c == 'attributes' or c=='categories':
        continue
    if is_categorical(restaurants_clean[c].unique()):
        categorical.append(c)
        
# Handling categorical feature: state
for c in categorical:
    restaurants_clean[c] = restaurants_clean[c].astype('category')
    dummies = pd.get_dummies(restaurants_clean[c])
    restaurants_clean = restaurants_clean.join(dummies)
    restaurants_clean = restaurants_clean.drop([c], axis=1)

/usr/local/lib/python2.7/site-packages/IPython/kernel/__main__.py:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [18]:
restaurants_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13707 entries, mVHrayjG3uZ_RLHkLj-AMg to qrgod2lrYnxHwNWC_YYTyQ
Columns: 208 entries, attributes to very_loud
dtypes: bool(1), float64(194), int64(2), object(11)
memory usage: 21.8+ MB


In [19]:
# Dropping the target with less than 1000 occurences
count = restaurants_clean.target.value_counts()
classes = count[count >1000].index.values

# Warning: The class 0 stands for no nationality
restaurants_clean['target_top'] = restaurants_clean.apply(lambda x: x['target'] if x['target'] in classes else 0, axis=1)
classes_name = [nationalities[i - 1] for i in classes[1:]]
classes_name

['Mexican', 'Italian']

In [20]:
# Changing the label of the target classes according to the selected classes
classes_map = {k:i for i,k in enumerate(classes)}
classes_s = range(0,len(classes))

restaurants_clean['target_top'] = restaurants_clean.apply(lambda x: classes_map[x['target_top']], axis=1)
restaurants_clean.head(5)

attributes  \
business_id                                                                 
mVHrayjG3uZ_RLHkLj-AMg  {u'Alcohol': u'full_bar', u'Noise Level': u'av...   
KayYbHCt-RkbGcPdGOThNg  {u'Alcohol': u'full_bar', u'Noise Level': u'lo...   
fNGIbpazjTRdXgwRY_NIXA  {u'Alcohol': u'full_bar', u'Noise Level': u'av...   
b9WZJp5L1RZr4F1nxclOoQ  {u'Alcohol': u'none', u'Noise Level': u'averag...   
zaXDakTd3RXyOa7sMrUE1g  {u'Take-out': True, u'Price Range': 1, u'Outdo...   

                                                               categories  \
business_id                                                                 
mVHrayjG3uZ_RLHkLj-AMg  [Bars, American (New), Nightlife, Lounges, Res...   
KayYbHCt-RkbGcPdGOThNg  [Bars, American (Traditional), Nightlife, Rest...   
fNGIbpazjTRdXgwRY_NIXA  [Bars, American (Traditional), Nightlife, Loun...   
b9WZJp5L1RZr4F1nxclOoQ                  [Breakfast & Brunch, Restaurants]   
zaXDakTd3RXyOa7sMrUE1g                               [Cafes, Restaurants]   

                         latitude  longitude  open  review_count  stars  0-0  \
business_id                                                                    
mVHrayjG3uZ_RLHkLj-AMg  40.408735 -79.866351  True            11    4.5    0   
KayYbHCt-RkbGcPdGOThNg  40.415517 -80.067534  True            15    4.0    0   
fNGIbpazjTRdXgwRY_NIXA  40.396469 -80.084942  True             5    4.0    0   
b9WZJp5L1RZr4F1nxclOoQ  40.396744 -80.084800  True            38    4.5    0   
zaXDakTd3RXyOa7sMrUE1g  40.404638 -80.089985  True             5    4.0    0   

                        0-1  0-2     ...      dressy  formal  beer_and_wine  \
business_id                          ...                                      
mVHrayjG3uZ_RLHkLj-AMg    0    0     ...           0       0              0   
KayYbHCt-RkbGcPdGOThNg    0    0     ...           0       0              0   
fNGIbpazjTRdXgwRY_NIXA    0    0     ...           0       0              0   
b9WZJp5L1RZr4F1nxclOoQ    0    0     ...           0       0              0   
zaXDakTd3RXyOa7sMrUE1g    0    0     ...           0       0              0   

                        full_bar  none  average  loud  quiet  very_loud  \
business_id                                                               
mVHrayjG3uZ_RLHkLj-AMg         1     0        1     0      0          0   
KayYbHCt-RkbGcPdGOThNg         1     0        0     1      0          0   
fNGIbpazjTRdXgwRY_NIXA         1     0        1     0      0          0   
b9WZJp5L1RZr4F1nxclOoQ         0     1        1     0      0          0   
zaXDakTd3RXyOa7sMrUE1g         0     1        1     0      0          0   

                        target_top  
business_id                         
mVHrayjG3uZ_RLHkLj-AMg           0  
KayYbHCt-RkbGcPdGOThNg           0  
fNGIbpazjTRdXgwRY_NIXA           0  
b9WZJp5L1RZr4F1nxclOoQ           0  
zaXDakTd3RXyOa7sMrUE1g           0  

[5 rows x 209 columns]

In [34]:
data_pca.shape

(13707, 27)

In [24]:
# Drop irrelevant features
data_exp = restaurants_clean.reset_index()
data_exp = data_exp.drop(['business_id', 'categories', 'attributes', 'target'], axis=1)

# Split train/test set
mask = np.random.rand(len(data_exp)) < 0.8
train_set = data_exp[mask]
test_set = data_exp[~mask]

print test_set.target_top.value_counts()
print train_set.target_top.value_counts()


0    2255
1     301
2     196
dtype: int64
0    8895
1    1250
2     810
dtype: int64


In [60]:
# Multiclass Logistic Regression
from sklearn.linear_model import LogisticRegression


y = train_set['target_top']
X = train_set.drop(['target_top'], axis=1)

lreg = LogisticRegression(penalty='l1', solver='lbfgs', multi_class='ovr')
clf = lreg.fit(X, y)

# Testing

y_test = test_set['target_top']
X_test = test_set.drop(['target_top'], axis=1)

y_test_pred = clf.predict(X_test)
y_score = clf.decision_function(X_test)


AttributeError: 'DummyClassifier' object has no attribute 'decision_function'

In [57]:
# PCA 
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression


# Dimensionality reduction
pca = PCA(n_components=0.999)
data_pca = pca.fit_transform(data_exp.drop(['target_top'], axis=1))

train_pca_set = data_pca[mask]
test_pca_set = data_pca[~mask]

y = train_set['target_top']
X = train_pca_set

lreg = LogisticRegression(penalty='l1', solver='lbfgs', multi_class='ovr')
clf = lreg.fit(X, y)

# Testing

y_test = test_set['target_top']
X_test = test_pca_set

y_test_pred = clf.predict(X_test)
y_score_pca = clf.decision_function(X_test)

In [46]:
# Plotting the confusion matrix

from sklearn.metrics import confusion_matrix

target_names = ['None'] + classes_name

def plot_confusion_matrix(cm, title='Confusion matrix', cmap=plt.cm.Blues):
    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(target_names))
    plt.xticks(tick_marks, target_names, rotation=45)
    plt.yticks(tick_marks, target_names)
    plt.tight_layout()
    plt.ylabel('True label')
    plt.xlabel('Predicted label')



# Compute confusion matrix
cm = confusion_matrix(y_test, y_test_pred)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
plt.figure()
plot_confusion_matrix(cm)

# Normalize the confusion matrix by row (i.e by the number of samples
# in each class)
cm_normalized = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)
plt.figure()
plot_confusion_matrix(cm_normalized, title='Normalized confusion matrix')

plt.show()

Confusion matrix, without normalization
[[2245    2    8]
 [ 296    5    0]
 [ 193    0    3]]
Normalized confusion matrix

/usr/local/lib/python2.7/site-packages/matplotlib/tight_layout.py:225: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")
/usr/local/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):



[[  9.96e-01   8.87e-04   3.55e-03]
 [  9.83e-01   1.66e-02   0.00e+00]
 [  9.85e-01   0.00e+00   1.53e-02]]


In [84]:
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize

# Binarize the output
y_bin = label_binarize(y, classes=classes_s)
y_test_bin = label_binarize(y_test, classes=classes_s)
n_classes = y_bin.shape[1]

# Names of the classes
target_names = ['None'] + classes_name

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(len(target_names)):
    fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test_bin.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])

# Plot ROC curve
plt.figure()
for i in range(n_classes):
    plt.plot(fpr[i], tpr[i], label='ROC curve of class {0} (area = {1:0.2f})'
                                   ''.format(target_names[i], roc_auc[i]))

plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('multi-class ROC curve')
plt.legend(loc="lower right")
plt.show()

In [81]:
# Metrics and comparaison with dummy models (always predicting 0 for example)

from sklearn import metrics

print metrics.precision_score(y_test, np.zeros(y_test.shape[0]))
print metrics.precision_score(y_test, y_test_pred)


0.671423029551
0.726111608768


/usr/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1082: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sample_weight)
/usr/local/lib/python2.7/site-packages/sklearn/metrics/classification.py:1082: DeprecationWarning: The default `weighted` averaging is deprecated, and from version 0.18, use of precision, recall or F-score with multiclass or multilabel data or pos_label=None will result in an exception. Please set an explicit value for `average`, one of (None, 'micro', 'macro', 'weighted', 'samples'). In cross validation use, for instance, scoring="f1_weighted" instead of scoring="f1".
  sample_weight=sampl

In [63]:
y_score

array([[ 1.8 , -2.28, -3.34],
       [ 2.4 , -2.73, -4.05],
       [ 1.33, -2.99, -1.83],
       ..., 
       [ 1.6 , -1.06, -4.09],
       [ 0.63, -1.89, -1.51],
       [ 1.34, -2.45, -2.26]])

In [69]:
len(restaurant_categories_set)

261

In [70]:
X.shape

(10955, 205)